include "synapse_mocap.fbs";
include "synapse_topics.fbs";

namespace synapse.log;

table SchemaRecord {
  name:string;
  bfbs:[ubyte];
}

table FlightSnapshotRecord {
  monotonic_us:ulong;
  payload:synapse.topic.FlightSnapshot;
}

table MotorOutputRecord {
  monotonic_us:ulong;
  payload:synapse.topic.MotorOutput;
}

table MocapDefinitionRecord {
  monotonic_us:ulong;
  payload:synapse.topic.MocapDefinition;
}

table MocapFrameRecord {
  monotonic_us:ulong;
  payload:synapse.topic.MocapFrame;
}

union RecordPayload {
  SchemaRecord,
  FlightSnapshotRecord,
  MotorOutputRecord,
  MocapDefinitionRecord,
  MocapFrameRecord
}

table LogRecord {
  record:RecordPayload;
}

root_type LogRecord;
file_identifier "SYLG";
