# automatically generated by the FlatBuffers compiler, do not modify

# namespace: topic

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ControlStatus(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 24

    # ControlStatus
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ControlStatus
    def RcStampMs(self): return self._tab.Get(flatbuffers.number_types.Int64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # ControlStatus
    def ThrottleUs(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # ControlStatus
    def RcLinkQuality(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # ControlStatus
    def FlightMode(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(13))
    # ControlStatus
    def Armed(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(14))
    # ControlStatus
    def RcValid(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(15))
    # ControlStatus
    def RcStale(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # ControlStatus
    def ImuOk(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(17))
    # ControlStatus
    def ArmSwitch(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(18))

def CreateControlStatus(builder, rcStampMs, throttleUs, rcLinkQuality, flightMode, armed, rcValid, rcStale, imuOk, armSwitch):
    builder.Prep(8, 24)
    builder.Pad(5)
    builder.PrependBool(armSwitch)
    builder.PrependBool(imuOk)
    builder.PrependBool(rcStale)
    builder.PrependBool(rcValid)
    builder.PrependBool(armed)
    builder.PrependUint8(flightMode)
    builder.PrependUint8(rcLinkQuality)
    builder.PrependInt32(throttleUs)
    builder.PrependInt64(rcStampMs)
    return builder.Offset()
