# automatically generated by the FlatBuffers compiler, do not modify

# namespace: topic

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FlightSnapshot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FlightSnapshot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFlightSnapshot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FlightSnapshot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FlightSnapshot
    def Gyro(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from synapse.topic.Vec3f import Vec3f
            obj = Vec3f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FlightSnapshot
    def Accel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from synapse.topic.Vec3f import Vec3f
            obj = Vec3f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FlightSnapshot
    def Rc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from synapse.topic.RcChannels16 import RcChannels16
            obj = RcChannels16()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FlightSnapshot
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from synapse.topic.ControlStatus import ControlStatus
            obj = ControlStatus()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FlightSnapshot
    def Attitude(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from synapse.topic.AttitudeEuler import AttitudeEuler
            obj = AttitudeEuler()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FlightSnapshot
    def AttitudeDesired(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            from synapse.topic.AttitudeEuler import AttitudeEuler
            obj = AttitudeEuler()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FlightSnapshot
    def RateDesired(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            from synapse.topic.RateTriplet import RateTriplet
            obj = RateTriplet()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FlightSnapshot
    def RateCmd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = o + self._tab.Pos
            from synapse.topic.RateTriplet import RateTriplet
            obj = RateTriplet()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def FlightSnapshotStart(builder):
    builder.StartObject(8)

def Start(builder):
    FlightSnapshotStart(builder)

def FlightSnapshotAddGyro(builder, gyro):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(gyro), 0)

def AddGyro(builder, gyro):
    FlightSnapshotAddGyro(builder, gyro)

def FlightSnapshotAddAccel(builder, accel):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(accel), 0)

def AddAccel(builder, accel):
    FlightSnapshotAddAccel(builder, accel)

def FlightSnapshotAddRc(builder, rc):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(rc), 0)

def AddRc(builder, rc):
    FlightSnapshotAddRc(builder, rc)

def FlightSnapshotAddStatus(builder, status):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(status), 0)

def AddStatus(builder, status):
    FlightSnapshotAddStatus(builder, status)

def FlightSnapshotAddAttitude(builder, attitude):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(attitude), 0)

def AddAttitude(builder, attitude):
    FlightSnapshotAddAttitude(builder, attitude)

def FlightSnapshotAddAttitudeDesired(builder, attitudeDesired):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(attitudeDesired), 0)

def AddAttitudeDesired(builder, attitudeDesired):
    FlightSnapshotAddAttitudeDesired(builder, attitudeDesired)

def FlightSnapshotAddRateDesired(builder, rateDesired):
    builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(rateDesired), 0)

def AddRateDesired(builder, rateDesired):
    FlightSnapshotAddRateDesired(builder, rateDesired)

def FlightSnapshotAddRateCmd(builder, rateCmd):
    builder.PrependStructSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(rateCmd), 0)

def AddRateCmd(builder, rateCmd):
    FlightSnapshotAddRateCmd(builder, rateCmd)

def FlightSnapshotEnd(builder):
    return builder.EndObject()

def End(builder):
    return FlightSnapshotEnd(builder)
