# automatically generated by the FlatBuffers compiler, do not modify

# namespace: topic

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MocapRigidBodySample(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 40

    # MocapRigidBodySample
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MocapRigidBodySample
    def Id(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # MocapRigidBodySample
    def Position(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 4)
        return obj

    # MocapRigidBodySample
    def Attitude(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 16)
        return obj

    # MocapRigidBodySample
    def Residual(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(32))
    # MocapRigidBodySample
    def TrackingValid(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(36))

def CreateMocapRigidBodySample(builder, id, position_x, position_y, position_z, attitude_x, attitude_y, attitude_z, attitude_w, residual, trackingValid):
    builder.Prep(4, 40)
    builder.Pad(3)
    builder.PrependBool(trackingValid)
    builder.PrependFloat32(residual)
    builder.Prep(4, 16)
    builder.PrependFloat32(attitude_w)
    builder.PrependFloat32(attitude_z)
    builder.PrependFloat32(attitude_y)
    builder.PrependFloat32(attitude_x)
    builder.Prep(4, 12)
    builder.PrependFloat32(position_z)
    builder.PrependFloat32(position_y)
    builder.PrependFloat32(position_x)
    builder.PrependInt32(id)
    return builder.Offset()
