# automatically generated by the FlatBuffers compiler, do not modify

# namespace: topic

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MocapSegmentSample(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 40

    # MocapSegmentSample
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MocapSegmentSample
    def SkeletonId(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # MocapSegmentSample
    def SegmentId(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # MocapSegmentSample
    def Position(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 8)
        return obj

    # MocapSegmentSample
    def Attitude(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 20)
        return obj

    # MocapSegmentSample
    def TrackingValid(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(36))

def CreateMocapSegmentSample(builder, skeletonId, segmentId, position_x, position_y, position_z, attitude_x, attitude_y, attitude_z, attitude_w, trackingValid):
    builder.Prep(4, 40)
    builder.Pad(3)
    builder.PrependBool(trackingValid)
    builder.Prep(4, 16)
    builder.PrependFloat32(attitude_w)
    builder.PrependFloat32(attitude_z)
    builder.PrependFloat32(attitude_y)
    builder.PrependFloat32(attitude_x)
    builder.Prep(4, 12)
    builder.PrependFloat32(position_z)
    builder.PrependFloat32(position_y)
    builder.PrependFloat32(position_x)
    builder.PrependInt32(segmentId)
    builder.PrependInt32(skeletonId)
    return builder.Offset()
