# automatically generated by the FlatBuffers compiler, do not modify

# namespace: topic

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MocapDefinition(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MocapDefinition()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMocapDefinition(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MocapDefinition
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MocapDefinition
    def Source(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MocapDefinition
    def FrameId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MocapDefinition
    def LabeledMarkers(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from synapse.topic.MocapMarkerDefinition import MocapMarkerDefinition
            obj = MocapMarkerDefinition()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MocapDefinition
    def LabeledMarkersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MocapDefinition
    def LabeledMarkersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # MocapDefinition
    def RigidBodies(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from synapse.topic.MocapRigidBodyDefinition import MocapRigidBodyDefinition
            obj = MocapRigidBodyDefinition()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MocapDefinition
    def RigidBodiesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MocapDefinition
    def RigidBodiesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # MocapDefinition
    def SkeletonSegments(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from synapse.topic.MocapSegmentDefinition import MocapSegmentDefinition
            obj = MocapSegmentDefinition()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MocapDefinition
    def SkeletonSegmentsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MocapDefinition
    def SkeletonSegmentsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def MocapDefinitionStart(builder):
    builder.StartObject(5)

def Start(builder):
    MocapDefinitionStart(builder)

def MocapDefinitionAddSource(builder, source):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(source), 0)

def AddSource(builder, source):
    MocapDefinitionAddSource(builder, source)

def MocapDefinitionAddFrameId(builder, frameId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(frameId), 0)

def AddFrameId(builder, frameId):
    MocapDefinitionAddFrameId(builder, frameId)

def MocapDefinitionAddLabeledMarkers(builder, labeledMarkers):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(labeledMarkers), 0)

def AddLabeledMarkers(builder, labeledMarkers):
    MocapDefinitionAddLabeledMarkers(builder, labeledMarkers)

def MocapDefinitionStartLabeledMarkersVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartLabeledMarkersVector(builder, numElems):
    return MocapDefinitionStartLabeledMarkersVector(builder, numElems)

def MocapDefinitionAddRigidBodies(builder, rigidBodies):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(rigidBodies), 0)

def AddRigidBodies(builder, rigidBodies):
    MocapDefinitionAddRigidBodies(builder, rigidBodies)

def MocapDefinitionStartRigidBodiesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRigidBodiesVector(builder, numElems):
    return MocapDefinitionStartRigidBodiesVector(builder, numElems)

def MocapDefinitionAddSkeletonSegments(builder, skeletonSegments):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(skeletonSegments), 0)

def AddSkeletonSegments(builder, skeletonSegments):
    MocapDefinitionAddSkeletonSegments(builder, skeletonSegments)

def MocapDefinitionStartSkeletonSegmentsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSkeletonSegmentsVector(builder, numElems):
    return MocapDefinitionStartSkeletonSegmentsVector(builder, numElems)

def MocapDefinitionEnd(builder):
    return builder.EndObject()

def End(builder):
    return MocapDefinitionEnd(builder)
