# automatically generated by the FlatBuffers compiler, do not modify

# namespace: topic

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MocapFrame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MocapFrame()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMocapFrame(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MocapFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MocapFrame
    def TimestampUs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # MocapFrame
    def FrameNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MocapFrame
    def LabeledMarkers(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 20
            from synapse.topic.MocapMarkerSample import MocapMarkerSample
            obj = MocapMarkerSample()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MocapFrame
    def LabeledMarkersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MocapFrame
    def LabeledMarkersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # MocapFrame
    def UnlabeledMarkers(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 20
            from synapse.topic.MocapMarkerSample import MocapMarkerSample
            obj = MocapMarkerSample()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MocapFrame
    def UnlabeledMarkersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MocapFrame
    def UnlabeledMarkersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # MocapFrame
    def RigidBodies(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 40
            from synapse.topic.MocapRigidBodySample import MocapRigidBodySample
            obj = MocapRigidBodySample()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MocapFrame
    def RigidBodiesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MocapFrame
    def RigidBodiesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # MocapFrame
    def SkeletonSegments(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 40
            from synapse.topic.MocapSegmentSample import MocapSegmentSample
            obj = MocapSegmentSample()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MocapFrame
    def SkeletonSegmentsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MocapFrame
    def SkeletonSegmentsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

def MocapFrameStart(builder):
    builder.StartObject(6)

def Start(builder):
    MocapFrameStart(builder)

def MocapFrameAddTimestampUs(builder, timestampUs):
    builder.PrependUint64Slot(0, timestampUs, 0)

def AddTimestampUs(builder, timestampUs):
    MocapFrameAddTimestampUs(builder, timestampUs)

def MocapFrameAddFrameNumber(builder, frameNumber):
    builder.PrependUint32Slot(1, frameNumber, 0)

def AddFrameNumber(builder, frameNumber):
    MocapFrameAddFrameNumber(builder, frameNumber)

def MocapFrameAddLabeledMarkers(builder, labeledMarkers):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(labeledMarkers), 0)

def AddLabeledMarkers(builder, labeledMarkers):
    MocapFrameAddLabeledMarkers(builder, labeledMarkers)

def MocapFrameStartLabeledMarkersVector(builder, numElems):
    return builder.StartVector(20, numElems, 4)

def StartLabeledMarkersVector(builder, numElems):
    return MocapFrameStartLabeledMarkersVector(builder, numElems)

def MocapFrameAddUnlabeledMarkers(builder, unlabeledMarkers):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(unlabeledMarkers), 0)

def AddUnlabeledMarkers(builder, unlabeledMarkers):
    MocapFrameAddUnlabeledMarkers(builder, unlabeledMarkers)

def MocapFrameStartUnlabeledMarkersVector(builder, numElems):
    return builder.StartVector(20, numElems, 4)

def StartUnlabeledMarkersVector(builder, numElems):
    return MocapFrameStartUnlabeledMarkersVector(builder, numElems)

def MocapFrameAddRigidBodies(builder, rigidBodies):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(rigidBodies), 0)

def AddRigidBodies(builder, rigidBodies):
    MocapFrameAddRigidBodies(builder, rigidBodies)

def MocapFrameStartRigidBodiesVector(builder, numElems):
    return builder.StartVector(40, numElems, 4)

def StartRigidBodiesVector(builder, numElems):
    return MocapFrameStartRigidBodiesVector(builder, numElems)

def MocapFrameAddSkeletonSegments(builder, skeletonSegments):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(skeletonSegments), 0)

def AddSkeletonSegments(builder, skeletonSegments):
    MocapFrameAddSkeletonSegments(builder, skeletonSegments)

def MocapFrameStartSkeletonSegmentsVector(builder, numElems):
    return builder.StartVector(40, numElems, 4)

def StartSkeletonSegmentsVector(builder, numElems):
    return MocapFrameStartSkeletonSegmentsVector(builder, numElems)

def MocapFrameEnd(builder):
    return builder.EndObject()

def End(builder):
    return MocapFrameEnd(builder)
