# automatically generated by the FlatBuffers compiler, do not modify

# namespace: topic

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MocapMarkerDefinition(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MocapMarkerDefinition()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMocapMarkerDefinition(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MocapMarkerDefinition
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MocapMarkerDefinition
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MocapMarkerDefinition
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MocapMarkerDefinition
    def Color(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def MocapMarkerDefinitionStart(builder):
    builder.StartObject(3)

def Start(builder):
    MocapMarkerDefinitionStart(builder)

def MocapMarkerDefinitionAddId(builder, id):
    builder.PrependInt32Slot(0, id, 0)

def AddId(builder, id):
    MocapMarkerDefinitionAddId(builder, id)

def MocapMarkerDefinitionAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    MocapMarkerDefinitionAddName(builder, name)

def MocapMarkerDefinitionAddColor(builder, color):
    builder.PrependUint32Slot(2, color, 0)

def AddColor(builder, color):
    MocapMarkerDefinitionAddColor(builder, color)

def MocapMarkerDefinitionEnd(builder):
    return builder.EndObject()

def End(builder):
    return MocapMarkerDefinitionEnd(builder)
