# automatically generated by the FlatBuffers compiler, do not modify

# namespace: topic

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MocapSegmentDefinition(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MocapSegmentDefinition()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMocapSegmentDefinition(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MocapSegmentDefinition
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MocapSegmentDefinition
    def SkeletonId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MocapSegmentDefinition
    def SkeletonName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MocapSegmentDefinition
    def SegmentId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MocapSegmentDefinition
    def SegmentName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def MocapSegmentDefinitionStart(builder):
    builder.StartObject(4)

def Start(builder):
    MocapSegmentDefinitionStart(builder)

def MocapSegmentDefinitionAddSkeletonId(builder, skeletonId):
    builder.PrependInt32Slot(0, skeletonId, 0)

def AddSkeletonId(builder, skeletonId):
    MocapSegmentDefinitionAddSkeletonId(builder, skeletonId)

def MocapSegmentDefinitionAddSkeletonName(builder, skeletonName):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(skeletonName), 0)

def AddSkeletonName(builder, skeletonName):
    MocapSegmentDefinitionAddSkeletonName(builder, skeletonName)

def MocapSegmentDefinitionAddSegmentId(builder, segmentId):
    builder.PrependInt32Slot(2, segmentId, 0)

def AddSegmentId(builder, segmentId):
    MocapSegmentDefinitionAddSegmentId(builder, segmentId)

def MocapSegmentDefinitionAddSegmentName(builder, segmentName):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(segmentName), 0)

def AddSegmentName(builder, segmentName):
    MocapSegmentDefinitionAddSegmentName(builder, segmentName)

def MocapSegmentDefinitionEnd(builder):
    return builder.EndObject()

def End(builder):
    return MocapSegmentDefinitionEnd(builder)
