# automatically generated by the FlatBuffers compiler, do not modify

# namespace: topic

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MocapRigidBodyDefinition(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MocapRigidBodyDefinition()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMocapRigidBodyDefinition(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MocapRigidBodyDefinition
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MocapRigidBodyDefinition
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MocapRigidBodyDefinition
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def MocapRigidBodyDefinitionStart(builder):
    builder.StartObject(2)

def Start(builder):
    MocapRigidBodyDefinitionStart(builder)

def MocapRigidBodyDefinitionAddId(builder, id):
    builder.PrependInt32Slot(0, id, 0)

def AddId(builder, id):
    MocapRigidBodyDefinitionAddId(builder, id)

def MocapRigidBodyDefinitionAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    MocapRigidBodyDefinitionAddName(builder, name)

def MocapRigidBodyDefinitionEnd(builder):
    return builder.EndObject()

def End(builder):
    return MocapRigidBodyDefinitionEnd(builder)
