# automatically generated by the FlatBuffers compiler, do not modify

# namespace: topic

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MocapMarkerSample(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 20

    # MocapMarkerSample
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MocapMarkerSample
    def Id(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # MocapMarkerSample
    def Position(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 4)
        return obj

    # MocapMarkerSample
    def Residual(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))

def CreateMocapMarkerSample(builder, id, position_x, position_y, position_z, residual):
    builder.Prep(4, 20)
    builder.PrependFloat32(residual)
    builder.Prep(4, 12)
    builder.PrependFloat32(position_z)
    builder.PrependFloat32(position_y)
    builder.PrependFloat32(position_x)
    builder.PrependInt32(id)
    return builder.Offset()
