# automatically generated by the FlatBuffers compiler, do not modify

# namespace: topic

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MotorRaw4u16(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # MotorRaw4u16
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MotorRaw4u16
    def M0(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # MotorRaw4u16
    def M1(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # MotorRaw4u16
    def M2(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # MotorRaw4u16
    def M3(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(6))

def CreateMotorRaw4u16(builder, m0, m1, m2, m3):
    builder.Prep(2, 8)
    builder.PrependUint16(m3)
    builder.PrependUint16(m2)
    builder.PrependUint16(m1)
    builder.PrependUint16(m0)
    return builder.Offset()
