# automatically generated by the FlatBuffers compiler, do not modify

# namespace: topic

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MotorOutput(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MotorOutput()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMotorOutput(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MotorOutput
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MotorOutput
    def Motors(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from synapse.topic.MotorValues4f import MotorValues4f
            obj = MotorValues4f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MotorOutput
    def Raw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from synapse.topic.MotorRaw4u16 import MotorRaw4u16
            obj = MotorRaw4u16()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MotorOutput
    def Armed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # MotorOutput
    def TestMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def MotorOutputStart(builder):
    builder.StartObject(4)

def Start(builder):
    MotorOutputStart(builder)

def MotorOutputAddMotors(builder, motors):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(motors), 0)

def AddMotors(builder, motors):
    MotorOutputAddMotors(builder, motors)

def MotorOutputAddRaw(builder, raw):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(raw), 0)

def AddRaw(builder, raw):
    MotorOutputAddRaw(builder, raw)

def MotorOutputAddArmed(builder, armed):
    builder.PrependBoolSlot(2, armed, 0)

def AddArmed(builder, armed):
    MotorOutputAddArmed(builder, armed)

def MotorOutputAddTestMode(builder, testMode):
    builder.PrependBoolSlot(3, testMode, 0)

def AddTestMode(builder, testMode):
    MotorOutputAddTestMode(builder, testMode)

def MotorOutputEnd(builder):
    return builder.EndObject()

def End(builder):
    return MotorOutputEnd(builder)
