# automatically generated by the FlatBuffers compiler, do not modify

# namespace: topic

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MotorValues4f(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # MotorValues4f
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MotorValues4f
    def M0(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # MotorValues4f
    def M1(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # MotorValues4f
    def M2(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # MotorValues4f
    def M3(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))

def CreateMotorValues4f(builder, m0, m1, m2, m3):
    builder.Prep(4, 16)
    builder.PrependFloat32(m3)
    builder.PrependFloat32(m2)
    builder.PrependFloat32(m1)
    builder.PrependFloat32(m0)
    return builder.Offset()
