# automatically generated by the FlatBuffers compiler, do not modify

# namespace: topic

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RateTriplet(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 12

    # RateTriplet
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RateTriplet
    def Roll(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # RateTriplet
    def Pitch(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # RateTriplet
    def Yaw(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateRateTriplet(builder, roll, pitch, yaw):
    builder.Prep(4, 12)
    builder.PrependFloat32(yaw)
    builder.PrependFloat32(pitch)
    builder.PrependFloat32(roll)
    return builder.Offset()
