# automatically generated by the FlatBuffers compiler, do not modify

# namespace: topic

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RcChannels16(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 64

    # RcChannels16
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RcChannels16
    def Ch0(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # RcChannels16
    def Ch1(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # RcChannels16
    def Ch2(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # RcChannels16
    def Ch3(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # RcChannels16
    def Ch4(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # RcChannels16
    def Ch5(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(20))
    # RcChannels16
    def Ch6(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(24))
    # RcChannels16
    def Ch7(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(28))
    # RcChannels16
    def Ch8(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(32))
    # RcChannels16
    def Ch9(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(36))
    # RcChannels16
    def Ch10(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(40))
    # RcChannels16
    def Ch11(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(44))
    # RcChannels16
    def Ch12(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(48))
    # RcChannels16
    def Ch13(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(52))
    # RcChannels16
    def Ch14(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(56))
    # RcChannels16
    def Ch15(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(60))

def CreateRcChannels16(builder, ch0, ch1, ch2, ch3, ch4, ch5, ch6, ch7, ch8, ch9, ch10, ch11, ch12, ch13, ch14, ch15):
    builder.Prep(4, 64)
    builder.PrependInt32(ch15)
    builder.PrependInt32(ch14)
    builder.PrependInt32(ch13)
    builder.PrependInt32(ch12)
    builder.PrependInt32(ch11)
    builder.PrependInt32(ch10)
    builder.PrependInt32(ch9)
    builder.PrependInt32(ch8)
    builder.PrependInt32(ch7)
    builder.PrependInt32(ch6)
    builder.PrependInt32(ch5)
    builder.PrependInt32(ch4)
    builder.PrependInt32(ch3)
    builder.PrependInt32(ch2)
    builder.PrependInt32(ch1)
    builder.PrependInt32(ch0)
    return builder.Offset()
