# automatically generated by the FlatBuffers compiler, do not modify

# namespace: topic

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VehicleOpticalFlowVel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VehicleOpticalFlowVel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVehicleOpticalFlowVel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VehicleOpticalFlowVel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VehicleOpticalFlowVel
    def Data(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from synapse.topic.VehicleOpticalFlowVelData import VehicleOpticalFlowVelData
            obj = VehicleOpticalFlowVelData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def VehicleOpticalFlowVelStart(builder):
    builder.StartObject(1)

def Start(builder):
    VehicleOpticalFlowVelStart(builder)

def VehicleOpticalFlowVelAddData(builder, data):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder, data):
    VehicleOpticalFlowVelAddData(builder, data)

def VehicleOpticalFlowVelEnd(builder):
    return builder.EndObject()

def End(builder):
    return VehicleOpticalFlowVelEnd(builder)
