# automatically generated by the FlatBuffers compiler, do not modify

# namespace: topic

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VehicleOpticalFlowData(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 56

    # VehicleOpticalFlowData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VehicleOpticalFlowData
    def TimestampUs(self): return self._tab.Get(flatbuffers.number_types.Int64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # VehicleOpticalFlowData
    def PixelFlow(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 8)
        return obj

    # VehicleOpticalFlowData
    def DeltaAngle(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 16)
        return obj

    # VehicleOpticalFlowData
    def DistanceM(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(28))
    # VehicleOpticalFlowData
    def IntegrationTimespanUs(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(32))
    # VehicleOpticalFlowData
    def Quality(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(36))
    # VehicleOpticalFlowData
    def MaxFlowRate(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(40))
    # VehicleOpticalFlowData
    def MinGroundDistance(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(44))
    # VehicleOpticalFlowData
    def MaxGroundDistance(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(48))

def CreateVehicleOpticalFlowData(builder, timestampUs, pixelFlow_x, pixelFlow_y, deltaAngle_x, deltaAngle_y, deltaAngle_z, distanceM, integrationTimespanUs, quality, maxFlowRate, minGroundDistance, maxGroundDistance):
    builder.Prep(8, 56)
    builder.Pad(4)
    builder.PrependFloat32(maxGroundDistance)
    builder.PrependFloat32(minGroundDistance)
    builder.PrependFloat32(maxFlowRate)
    builder.Pad(3)
    builder.PrependUint8(quality)
    builder.PrependUint32(integrationTimespanUs)
    builder.PrependFloat32(distanceM)
    builder.Prep(4, 12)
    builder.PrependFloat32(deltaAngle_z)
    builder.PrependFloat32(deltaAngle_y)
    builder.PrependFloat32(deltaAngle_x)
    builder.Prep(4, 8)
    builder.PrependFloat32(pixelFlow_y)
    builder.PrependFloat32(pixelFlow_x)
    builder.PrependInt64(timestampUs)
    return builder.Offset()
