# automatically generated by the FlatBuffers compiler, do not modify

# namespace: topic

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VehicleOpticalFlow(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VehicleOpticalFlow()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVehicleOpticalFlow(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VehicleOpticalFlow
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VehicleOpticalFlow
    def Data(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from synapse.topic.VehicleOpticalFlowData import VehicleOpticalFlowData
            obj = VehicleOpticalFlowData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def VehicleOpticalFlowStart(builder):
    builder.StartObject(1)

def Start(builder):
    VehicleOpticalFlowStart(builder)

def VehicleOpticalFlowAddData(builder, data):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder, data):
    VehicleOpticalFlowAddData(builder, data)

def VehicleOpticalFlowEnd(builder):
    return builder.EndObject()

def End(builder):
    return VehicleOpticalFlowEnd(builder)
