# automatically generated by the FlatBuffers compiler, do not modify

# namespace: topic

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VehicleOpticalFlowVelData(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 56

    # VehicleOpticalFlowVelData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VehicleOpticalFlowVelData
    def TimestampUs(self): return self._tab.Get(flatbuffers.number_types.Int64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # VehicleOpticalFlowVelData
    def VelBody(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 8)
        return obj

    # VehicleOpticalFlowVelData
    def VelNe(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 16)
        return obj

    # VehicleOpticalFlowVelData
    def FlowRateUncompensated(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 24)
        return obj

    # VehicleOpticalFlowVelData
    def FlowRateCompensated(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 32)
        return obj

    # VehicleOpticalFlowVelData
    def GyroRate(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 40)
        return obj


def CreateVehicleOpticalFlowVelData(builder, timestampUs, velBody_x, velBody_y, velNe_x, velNe_y, flowRateUncompensated_x, flowRateUncompensated_y, flowRateCompensated_x, flowRateCompensated_y, gyroRate_x, gyroRate_y, gyroRate_z):
    builder.Prep(8, 56)
    builder.Pad(4)
    builder.Prep(4, 12)
    builder.PrependFloat32(gyroRate_z)
    builder.PrependFloat32(gyroRate_y)
    builder.PrependFloat32(gyroRate_x)
    builder.Prep(4, 8)
    builder.PrependFloat32(flowRateCompensated_y)
    builder.PrependFloat32(flowRateCompensated_x)
    builder.Prep(4, 8)
    builder.PrependFloat32(flowRateUncompensated_y)
    builder.PrependFloat32(flowRateUncompensated_x)
    builder.Prep(4, 8)
    builder.PrependFloat32(velNe_y)
    builder.PrependFloat32(velNe_x)
    builder.Prep(4, 8)
    builder.PrependFloat32(velBody_y)
    builder.PrependFloat32(velBody_x)
    builder.PrependInt64(timestampUs)
    return builder.Offset()
