# automatically generated by the FlatBuffers compiler, do not modify

# namespace: sil

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SimInput(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SimInput()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSimInput(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SimInputBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x59\x53\x49", size_prefixed=size_prefixed)

    # SimInput
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SimInput
    def Gyro(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from synapse.topic.Vec3f import Vec3f
            obj = Vec3f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SimInput
    def Accel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from synapse.topic.Vec3f import Vec3f
            obj = Vec3f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SimInput
    def Rc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from synapse.topic.RcChannels16 import RcChannels16
            obj = RcChannels16()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SimInput
    def RcLinkQuality(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # SimInput
    def RcValid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # SimInput
    def ImuValid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def SimInputStart(builder):
    builder.StartObject(6)

def Start(builder):
    SimInputStart(builder)

def SimInputAddGyro(builder, gyro):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(gyro), 0)

def AddGyro(builder, gyro):
    SimInputAddGyro(builder, gyro)

def SimInputAddAccel(builder, accel):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(accel), 0)

def AddAccel(builder, accel):
    SimInputAddAccel(builder, accel)

def SimInputAddRc(builder, rc):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(rc), 0)

def AddRc(builder, rc):
    SimInputAddRc(builder, rc)

def SimInputAddRcLinkQuality(builder, rcLinkQuality):
    builder.PrependUint8Slot(3, rcLinkQuality, 0)

def AddRcLinkQuality(builder, rcLinkQuality):
    SimInputAddRcLinkQuality(builder, rcLinkQuality)

def SimInputAddRcValid(builder, rcValid):
    builder.PrependBoolSlot(4, rcValid, 0)

def AddRcValid(builder, rcValid):
    SimInputAddRcValid(builder, rcValid)

def SimInputAddImuValid(builder, imuValid):
    builder.PrependBoolSlot(5, imuValid, 0)

def AddImuValid(builder, imuValid):
    SimInputAddImuValid(builder, imuValid)

def SimInputEnd(builder):
    return builder.EndObject()

def End(builder):
    return SimInputEnd(builder)
